### ISSUE TITLE
Question: why does `Tensor#apply` return a value wrapped in `IO` effect? 

### ISSUE THREAD

**Issue by i10416** [EmergentOrder/onnx-scala#377]
Why does `Tensor#apply` return a value wrapped in `IO` effect? 

Is there any resource allocation or unsafe invocation to native land?

**Comment by EmergentOrder** [comment]
Yes, there is native resource allocation, under the hood ONNX Runtime is used and data needs to copied from the JVM into native memory. 
In addition to this, the transition to using IO here allows for the Java and JavaScript APIs to be unified, because onnxruntime-web and onnxruntime-node return Promises, which cannot be awaited because blocking is not allowed in ScalaJS (see: https://github.com/scala-js/scala-js/issues/186#issuecomment-33732043 ).
